version: '3.3'

services:

  app:
    build: .
    image: nodeapp
    ports: 
      - 81:3000
    # networks:
    #   - nodemernapp
        # aliases:
          # - "mongo_db"
          # driver: bridge
    environment:
      - MONGO_URI=mongodb://db/nodeapp


  db:
    image: "mongo:3.0.15"
    ports:
      - '27017:27017'
    volumes:
      - mongo-db:/data/db
    # networks:
    #   nodemernapp:
        # aliases:
        #   - "mongo_db"
        # driver: bridge

volumes:
  mongo-db:

networks:
  nodemernapp:
    driver: bridge


